#slightly modified Defines.mk from src directory

#common
DEFINES := \
MIDI_SYSEX_ARRAY_SIZE=45

BOARD_TYPE := opendeck

#board specific
ifeq ($(BOARD_TYPE), opendeck)
    MCU := atmega32u4
    BOARD := BOARD_OPEN_DECK
    DEFINES += LED_FADING_SUPPORTED
    DEFINES += LED_EXT_INVERT
    DEFINES += USE_MUX
    DEFINES += IN_MATRIX
    DEFINES += OUT_MATRIX
    DEFINES += LED_INDICATORS
    HARDWARE_VERSION_MAJOR := 1
    HARDWARE_VERSION_MINOR := 2
    DEFINES += DIN_MIDI_SUPPORTED
    DEFINES += UART_MIDI_CHANNEL=0
else ifeq ($(BOARD_TYPE), tannin)
    MCU := atmega32u4
    BOARD := BOARD_TANNIN
    DEFINES += LED_FADING_SUPPORTED
    DEFINES += LED_EXT_INVERT
    DEFINES += USE_MUX
    DEFINES += IN_MATRIX
    DEFINES += OUT_MATRIX
    HARDWARE_VERSION_MAJOR := 3
    HARDWARE_VERSION_MINOR := 0
else ifeq ($(BOARD_TYPE), leonardo)
    MCU := atmega32u4
    BOARD := BOARD_A_LEO
    DEFINES += LED_INT_INVERT
    DEFINES += LED_INDICATORS
    HARDWARE_VERSION_MAJOR := 1
    HARDWARE_VERSION_MINOR := 0
    DEFINES += DIN_MIDI_SUPPORTED
    DEFINES += UART_MIDI_CHANNEL=0
else ifeq ($(BOARD_TYPE), pro_micro)
    MCU := atmega32u4
    BOARD := BOARD_A_PRO_MICRO
    DEFINES += LED_INT_INVERT
    HARDWARE_VERSION_MAJOR := 1
    HARDWARE_VERSION_MINOR := 0
    DEFINES += LED_INDICATORS
    DEFINES += DIN_MIDI_SUPPORTED
    DEFINES += UART_MIDI_CHANNEL=0
else ifeq ($(BOARD_TYPE), kodama)
    MCU := atmega32u4
    BOARD := BOARD_KODAMA
    DEFINES += USE_MUX
    DEFINES += LED_EXT_INVERT
    HARDWARE_VERSION_MAJOR := 1
    HARDWARE_VERSION_MINOR := 0
else ifeq ($(BOARD_TYPE), bergamot)
    MCU := atmega32u4
    BOARD := BOARD_BERGAMOT
    DEFINES += USE_MUX
    HARDWARE_VERSION_MAJOR := 1
    HARDWARE_VERSION_MINOR := 0
    DEFINES += TOUCHSCREEN_SUPPORTED
    DEFINES += UART_TOUCHSCREEN_CHANNEL=0
else ifeq ($(BOARD_TYPE), teensy2pp)
    MCU := at90usb1286
    BOARD := BOARD_T_2PP
    DEFINES += STRING_BUFFER_SIZE=40
    HARDWARE_VERSION_MAJOR := 1
    HARDWARE_VERSION_MINOR := 0
    DEFINES += DIN_MIDI_SUPPORTED
    DEFINES += UART_MIDI_CHANNEL=0
else ifeq ($(BOARD_TYPE), mega)
    MCU := atmega2560
    BOARD := BOARD_A_MEGA
    DEFINES += STRING_BUFFER_SIZE=40
    DEFINES += TOUCHSCREEN_SUPPORTED
    HARDWARE_VERSION_MAJOR := 1
    HARDWARE_VERSION_MINOR := 0
    DEFINES += DIN_MIDI_SUPPORTED
    DEFINES += UART_USB_LINK_CHANNEL=0
    DEFINES += UART_MIDI_CHANNEL=1
    DEFINES += UART_TOUCHSCREEN_CHANNEL=1
else ifeq ($(BOARD_TYPE), uno)
    MCU := atmega328p
    BOARD := BOARD_A_UNO
    HARDWARE_VERSION_MAJOR := 1
    HARDWARE_VERSION_MINOR := 0
    DEFINES += UART_USB_LINK_CHANNEL=0
else ifeq ($(BOARD_TYPE), 16u2)
    MCU := atmega16u2
    BOARD := BOARD_A_xu2
    DEFINES += LED_INT_INVERT
    DEFINES += LED_INDICATORS
    HARDWARE_VERSION_MAJOR := 1
    HARDWARE_VERSION_MINOR := 0
    DEFINES += UART_USB_LINK_CHANNEL=0
else ifeq ($(BOARD_TYPE), 8u2)
    MCU := atmega8u2
    BOARD := BOARD_A_xu2
    DEFINES += LED_INT_INVERT
    DEFINES += LED_INDICATORS
    HARDWARE_VERSION_MAJOR := 1
    HARDWARE_VERSION_MINOR := 0
    DEFINES += UART_USB_LINK_CHANNEL=0
endif

#mcu specific
ifeq ($(MCU),atmega32u4)
    FUSE_UNLOCK := 0xff
    FUSE_EXT := 0xc8
    FUSE_HIGH := 0xd0
    FUSE_LOW := 0xff
    FUSE_LOCK := 0xef
    EEPROM_SIZE := 1024
    BOOT_START_ADDR := 0x7000
    FLASH_SIZE_START_ADDR := 0xAC
    FLASH_SIZE_END_ADDR := 0xB0
    DEFINES += UART_INTERFACES=1
    DEFINES += USB_SUPPORTED
else ifeq ($(MCU),at90usb1286)
    FUSE_UNLOCK := 0xff
    FUSE_EXT := 0xf8
    FUSE_HIGH := 0xd2
    FUSE_LOW := 0xff
    FUSE_LOCK := 0xef
    EEPROM_SIZE := 4096
    BOOT_START_ADDR := 0x1F000
    FLASH_SIZE_START_ADDR := 0x98
    FLASH_SIZE_END_ADDR := 0x9C
    DEFINES += UART_INTERFACES=1
    DEFINES += USB_SUPPORTED
else ifeq ($(MCU),atmega16u2)
    FUSE_UNLOCK := 0xff
    FUSE_EXT := 0xf8
    FUSE_HIGH := 0xd0
    FUSE_LOW := 0xff
    FUSE_LOCK := 0xef
    EEPROM_SIZE := 512
    FLASH_SIZE_START_ADDR := 0x74
    FLASH_SIZE_END_ADDR := 0x78
    BOOT_START_ADDR := 0x3000
    DEFINES += UART_INTERFACES=1
    DEFINES += USB_SUPPORTED
else ifeq ($(MCU),atmega8u2)
    FUSE_UNLOCK := 0xff
    FUSE_EXT := 0xf8
    FUSE_HIGH := 0xd3
    FUSE_LOW := 0xff
    FUSE_LOCK := 0xef
    EEPROM_SIZE := 512
    FLASH_SIZE_START_ADDR := 0x74
    FLASH_SIZE_END_ADDR := 0x78
    BOOT_START_ADDR := 0x1800
    DEFINES += UART_INTERFACES=1
    DEFINES += USB_SUPPORTED
else ifeq ($(MCU),atmega2560)
    FUSE_UNLOCK := 0xff
    FUSE_EXT := 0xfc
    FUSE_HIGH := 0xd2
    FUSE_LOW := 0xff
    FUSE_LOCK := 0xef
    EEPROM_SIZE := 4096
    FLASH_SIZE_START_ADDR := 0xE4
    FLASH_SIZE_END_ADDR := 0xE8
    BOOT_START_ADDR := 0x3F000
    DEFINES += UART_INTERFACES=2
else ifeq ($(MCU),atmega328p)
    FUSE_UNLOCK := 0xff
    FUSE_EXT := 0xfc
    FUSE_HIGH := 0xd2
    FUSE_LOW := 0xff
    FUSE_LOCK := 0xef
    EEPROM_SIZE := 1024
    FLASH_SIZE_START_ADDR := 0x68
    FLASH_SIZE_END_ADDR := 0x6C
    BOOT_START_ADDR := 0x7800
    DEFINES += UART_INTERFACES=1
endif

DEFINES += APP_LENGTH_LOCATION=$(FLASH_SIZE_START_ADDR)
DEFINES += BOOT_START_ADDR=$(BOOT_START_ADDR)
DEFINES += EEPROM_SIZE=$(EEPROM_SIZE)
#for database, total size is four bytes smaller than full eeprom
#one byte for reboot selection
#two for crc
DEFINES += LESSDB_SIZE=$(shell echo $(EEPROM_SIZE)-3 | bc)
DEFINES += $(BOARD)

DEFINES += HARDWARE_VERSION_MAJOR=$(HARDWARE_VERSION_MAJOR)
DEFINES += HARDWARE_VERSION_MINOR=$(HARDWARE_VERSION_MINOR)