ifeq (,$(findstring gen,$(TYPE)))
    SOURCES += \
    modules/core/modules/tinyusb/hw/mcu/nordic/nrfx/mdk/gcc_startup_nrf52840.S \
    modules/core/modules/tinyusb/hw/mcu/nordic/nrfx/mdk/system_nrf52840.c
endif