CONFIG_ZLIBS_DRIVERS_USB_MANUFACTURER="Shantea Controls"
CONFIG_ZLIBS_DRIVERS_USB_VID=0x1209
CONFIG_ZLIBS_DRIVERS_USB_SELF_POWERED=n
CONFIG_ZLIBS_DRIVERS_USB_REMOTE_WAKEUP=n
CONFIG_ZLIBS_DRIVERS_USB_MAX_POWER=100
