# Zephyr
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_ADC=y
CONFIG_POLL=y
CONFIG_I2C=y
CONFIG_USBD_MIDI2_CLASS=y
CONFIG_USBD_MIDI2_BUFFER_COUNT=16
CONFIG_USBD_MIDI2_TX_QUEUE_SIZE=256
CONFIG_MIDI2_UMP_STREAM_RESPONDER=y

# zlibs
CONFIG_ZLIBS_UTILS_LESSDB=y
CONFIG_ZLIBS_UTILS_EMUEEPROM=y
CONFIG_ZLIBS_UTILS_FILTERS=y
CONFIG_ZLIBS_UTILS_MIDI=y
CONFIG_ZLIBS_UTILS_MIDI_TRANSPORT_BLE=y
CONFIG_ZLIBS_UTILS_MIDI_TRANSPORT_SERIAL=y
CONFIG_ZLIBS_UTILS_MIDI_TRANSPORT_USB=y
CONFIG_ZLIBS_UTILS_SIGNALING=y
CONFIG_ZLIBS_UTILS_SIGNALING_MAX_POOL_SIZE=256
CONFIG_ZLIBS_UTILS_SIGNALING_THREAD_PRIORITY=0
CONFIG_ZLIBS_UTILS_SIGNALING_THREAD_STACK_SIZE=4096
CONFIG_ZLIBS_UTILS_SYSEX_CONF=y
CONFIG_ZLIBS_DRIVERS_UART_HW=y
CONFIG_ZLIBS_DRIVERS_USB_PID=0x8472
