analyzer:
  - --enable=sensitive
  - --enable=bugprone-use-after-move
  - --enable=bugprone-dangling-handle
  - --disable=bugprone-dynamic-static-initializers
  - --enable=clang-analyzer-cplusplus.NewDeleteLeaks
  - --enable=bugprone-incorrect-roundings
  - --enable=modernize-use-nullptr
  - --enable=modernize-use-override
  - --enable=cppcoreguidelines-pro-type-member-init
  - --enable=readability-magic-numbers
  - --disable=performance-enum-size
  - --disable=clang-diagnostic-reserved-identifier
  - --disable=clang-diagnostic-missing-field-initializers
  - --disable=clang-diagnostic-format-nonliteral
  - --disable=cppcoreguidelines-special-member-functions
  - --disable=cppcoreguidelines-avoid-const-or-ref-data-members
  - --disable=google-build-using-namespace
  - --enable=readability-braces-around-statements
  - --enable=readability-else-after-return
  - --enable=readability-inconsistent-declaration-parameter-name
  - --enable=readability-static-accessed-through-instance
  - --enable=readability-identifier-naming
  - --enable=modernize-use-equals-default
  - --enable=modernize-use-using
  - --enable=modernize-redundant-void-arg
  - --enable=modernize-concat-nested-namespaces
  - --enable=misc-redundant-expression
  - --enable=performance-inefficient-vector-operation
  - --checker-config=clang-tidy:readability-braces-around-statements:ShortStatementLines=0
  - --checker-config=clang-tidy:readability-identifier-naming:ClassCase=CamelCase
  - --checker-config=clang-tidy:readability-identifier-naming:ClassMemberCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:ClassMethodCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:ConstexprFunctionCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:ConstexprVariableCase=UPPER_CASE
  - --checker-config=clang-tidy:readability-identifier-naming:EnumConstantCase=CamelCase
  - --checker-config=clang-tidy:readability-identifier-naming:FunctionCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:GlobalConstantCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:GlobalPointerCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:GlobalVariableCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:LocalConstantCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:LocalConstantPointerCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:LocalVariableCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:MemberCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:NamespaceCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:PrivateMemberCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:PrivateMemberPrefix=_
  - --checker-config=clang-tidy:readability-identifier-naming:ProtectedMemberCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:ProtectedMemberPrefix=_
  - --checker-config=clang-tidy:readability-identifier-naming:StaticConstantCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:StaticVariableCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:StructCase=CamelCase
  - --checker-config=clang-tidy:readability-identifier-naming:PublicMemberCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:TemplateParameterCase=CamelCase
  - --checker-config=clang-tidy:readability-identifier-naming:VirtualMethodCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:ParameterCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:ConstantParameterCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:ConstantPointerParameterCase=lower_case
  - --checker-config=clang-tidy:readability-identifier-naming:PointerParameterCase=lower_case
  - --checker-config=clang-tidy:readability-inconsistent-declaration-parameter-name:Strict=true
  - --checker-config=clang-tidy:readability-identifier-naming:TypeAliasCase=CamelCase
  - --ignore=$ZEPHYR_WS/zenv/codechecker/skip.txt
  - --clean
  - --no-missing-checker-error

parse:
  - --ignore=$ZEPHYR_WS/zenv/codechecker/skip.txt
