manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: paradajz
      url-base: https://github.com/paradajz
    - name: olikraus
      url-base: https://github.com/olikraus
    - name: stm32duino
      url-base: https://github.com/stm32duino

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: bcf31c20f01f11609dbff940483d5172d7897691
      import: true
    - name: u8g2
      remote: olikraus
      revision: 8430f65c9e2bc7ca393bf0e9d8cf58a84ae081d7
      path: modules/u8g2
      submodules: true
    - name: zlibs
      remote: paradajz
      revision: 26fc27be354b4f9e2e9475c5084c324aafb9b9a4
      path: modules/zlibs
    - name: vl53l4cx
      remote: stm32duino
      revision: 8ef5e558f4617ac52f559563e9ffe285a8b345f8
      path: modules/vl53l4cx
