manifest:
  remotes:
    - name: paradajz
      url-base: https://github.com/paradajz
    - name: olikraus
      url-base: https://github.com/olikraus

  projects:
    - name: u8g2
      remote: olikraus
      revision: 8430f65c9e2bc7ca393bf0e9d8cf58a84ae081d7
      path: modules/u8g2
      submodules: true
    - name: zlibs
      remote: paradajz
      revision: 042b584e29c65a76106949ef057c4a379a7e847f
      path: modules/zlibs
