CONFIG_LOG=y

## zlibs
CONFIG_ZLIBS_UTILS_MIDI=y
CONFIG_ZLIBS_UTILS_LESSDB=y
CONFIG_ZLIBS_UTILS_EMUEEPROM=y
CONFIG_ZLIBS_DRIVERS_USB_HW=y
CONFIG_ZLIBS_DRIVERS_USB_MANUFACTURER="Shantea Controls"
CONFIG_ZLIBS_DRIVERS_USB_PRODUCT="OpenDeck"
CONFIG_ZLIBS_DRIVERS_USB_VID=0x1209
CONFIG_ZLIBS_DRIVERS_USB_PID=0x8472
CONFIG_ZLIBS_DRIVERS_USB_SELF_POWERED=n
CONFIG_ZLIBS_DRIVERS_USB_REMOTE_WAKEUP=n
CONFIG_ZLIBS_DRIVERS_USB_MAX_POWER=100

# usb midi
CONFIG_USBD_MIDI2_CLASS=y
CONFIG_MIDI2_UMP_STREAM_RESPONDER=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y
