# Zephyr
CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_GLIBCXX_LIBCPP=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_HWINFO=y
CONFIG_REBOOT=y
CONFIG_RETAINED_MEM=y
CONFIG_RETENTION=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_TIMESLICE_SIZE=10

# zlibs
CONFIG_ZLIBS_UTILS_MISC=y
CONFIG_ZLIBS_DRIVERS_USB_HW=y
CONFIG_ZLIBS_DRIVERS_USB_MANUFACTURER="Shantea Controls"
CONFIG_ZLIBS_DRIVERS_USB_VID=0x1209
CONFIG_ZLIBS_DRIVERS_USB_SELF_POWERED=n
CONFIG_ZLIBS_DRIVERS_USB_REMOTE_WAKEUP=n
CONFIG_ZLIBS_DRIVERS_USB_MAX_POWER=100
