CONFIG_LOG=y
CONFIG_BOOT_BANNER=y
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_USBD_MIDI2_LOG_LEVEL_WRN=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_UDC_DRIVER_LOG_LEVEL_ERR=y
CONFIG_LOG_MODE_IMMEDIATE=y

# Do not enable on RP2040!
# CONFIG_DEBUG_OPTIMIZATIONS=y
