CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_ADC=y
CONFIG_I2C=y
CONFIG_ZLIBS_DRIVERS_UART_HW=y
CONFIG_ZLIBS_UTILS_FILTERS=y
CONFIG_ZLIBS_UTILS_MISC=y
CONFIG_ZLIBS_UTILS_SIGNALING=y
CONFIG_ZLIBS_UTILS_SYSEX_CONF=y
CONFIG_REBOOT=y
