function(check_required_executables)
    foreach(executable ${ARGV})
        find_program(${executable}_result ${executable})
        if(${executable}_result)
            message(STATUS "Required executable ${executable} found at: ${${executable}_result}")
        else()
            message(FATAL_ERROR "Required executable ${executable} not found!")
        endif()
    endforeach()
endfunction()