ifeq (,$(findstring gen,$(TYPE)))
    SOURCES += \
    modules/core/modules/pico-sdk/src/rp2_common/pico_fix/rp2040_usb_device_enumeration/rp2040_usb_device_enumeration.c
endif

DEFINES += \
CFG_TUSB_MCU=OPT_MCU_RP2040