#!/bin/bash

#used to generate firmware UID for specified target
#call example: ./fw_uid_gen.sh fw_opendeck
#hash is generated by hashing the target name and cutting the output to 3 bytes
#after that, each byte is ANDed with 127: FWUID needs to be sent via MIDI sysex and values larger than 127 aren't allowed

if [ "$(uname)" == "Darwin" ]; then
    sha=gsha256sum
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    sha=sha256sum
fi

if [[ "${1}" =~ "fw" ]]; then
    app_type=1
elif [[ "${1}" =~ "boot" ]]; then
    app_type=0
else
    echo Incorrect argument
    exit 1
fi

targetname_hash=0x$(printf '%s' $1 | $sha | head -c 64 | cut -c -6)
printf '0x%02x%02x%02x%02x\n' "$app_type" "$((($targetname_hash >> 0) & 127))" "$((($targetname_hash >> 8) & 127))" "$((($targetname_hash >> 16) & 127))"