vpath application/%.cpp ../src/firmware
vpath board/%.cpp ../src/firmware

SOURCES_$(shell basename $(dir $(lastword $(MAKEFILE_LIST)))) := \
board/src/common/communication/USBOverSerial/USBOverSerial.cpp
