# Zephyr
CONFIG_GPIO=y
CONFIG_USE_DT_CODE_PARTITION=y
CONFIG_POLL=y
CONFIG_ASSERT=n
CONFIG_BOOT_BANNER=n
CONFIG_ERRNO=n
CONFIG_NO_RUNTIME_CHECKS=y
CONFIG_PRINTK=n
CONFIG_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_UART_INTERRUPT_DRIVEN=n
CONFIG_PICOLIBC_IO_LONG_LONG=n
